### ISSUE TITLE
There is issue in Driver_Home.php 

### ISSUE THREAD

**Issue by Ashwini-ux** [desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT#1]
In this file the total no.of ambulance   , notes are not displayed properly .
so , I am attaching the corrected file.
Please check and do changes

[Driver_Home.zip](https://github.com/desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT/files/5011627/Driver_Home.zip)

**Comment by ChaudhariKhushboo** [comment]
Great!
