### ISSUE TITLE
There is another issue in Driver_Home.php

### ISSUE THREAD

**Issue by ChaudhariKhushboo** [desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT#2]
In this File There is problem in fetching latitude and longitude of accident location at driver side.

**Comment by AratiPatil1212** [comment]
problem solved!!!

[Driver_Home.zip](https://github.com/desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT/files/5011970/Driver_Home.zip)
