### ISSUE TITLE
There is a issue in Driver_list_hos.php

### ISSUE THREAD

**Issue by nikitaharale17** [desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT#3]
Issue in calculating distance in kilometre . from accident location to hospital.

**Comment by AratiPatil1212** [comment]
solved!!!
[Driver_list_hos.zip](https://github.com/desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT/files/5011977/Driver_list_hos.zip)
[location.zip](https://github.com/desalerewa/SIH2020_IC464_LYFsavers_GitRepository_MLRIT/files/5011978/location.zip)
